//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZS2ServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class craft_blueprints
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ItemResref { get; set; }
        public Nullable<int> BaseAmount { get; set; }
        public Nullable<int> AdditionalAmount { get; set; }
        public Nullable<int> Skill { get; set; }
        public Nullable<int> BlueprintLevel { get; set; }
        public Nullable<int> XP { get; set; }
        public string Device { get; set; }
        public string Component1Name { get; set; }
        public Nullable<int> Component1Quantity { get; set; }
        public string Component1Resref { get; set; }
        public string Component2Name { get; set; }
        public Nullable<int> Component2Quantity { get; set; }
        public string Component2Resref { get; set; }
        public string Component3Name { get; set; }
        public Nullable<int> Component3Quantity { get; set; }
        public string Component3Resref { get; set; }
        public string Component4Name { get; set; }
        public Nullable<int> Component4Quantity { get; set; }
        public string Component4Resref { get; set; }
        public string Component5Name { get; set; }
        public Nullable<int> Component5Quantity { get; set; }
        public string Component5Resref { get; set; }
        public string Component6Name { get; set; }
        public Nullable<int> Component6Quantity { get; set; }
        public string Component6Resref { get; set; }
        public string Component7Name { get; set; }
        public Nullable<int> Component7Quantity { get; set; }
        public string Component7Resref { get; set; }
        public string Component8Name { get; set; }
        public Nullable<int> Component8Quantity { get; set; }
        public string Component8Resref { get; set; }
        public string Component9Name { get; set; }
        public Nullable<int> Component9Quantity { get; set; }
        public string Component9Resref { get; set; }
        public string Component10Name { get; set; }
        public Nullable<int> Component10Quantity { get; set; }
        public string Component10Resref { get; set; }
        public Nullable<int> MenuCategory { get; set; }
        public Nullable<int> Component1 { get; set; }
        public Nullable<int> Component2 { get; set; }
        public Nullable<int> Component3 { get; set; }
        public Nullable<int> Component4 { get; set; }
        public Nullable<int> Component5 { get; set; }
        public Nullable<int> Component6 { get; set; }
        public Nullable<int> Component7 { get; set; }
        public Nullable<int> Component8 { get; set; }
        public Nullable<int> Component9 { get; set; }
        public Nullable<int> Component10 { get; set; }
    }
}
