//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZS2ServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_log
    {
        public long ID { get; set; }
        public string DM_Name { get; set; }
        public string DM_Account { get; set; }
        public string DM_CDKey { get; set; }
        public string PC_Name { get; set; }
        public string PC_Account { get; set; }
        public string PC_CDKey { get; set; }
        public string Action { get; set; }
        public string ItemName { get; set; }
        public string ItemTag { get; set; }
        public string ItemResref { get; set; }
        public Nullable<long> GoldAmount { get; set; }
        public Nullable<int> XPAmount { get; set; }
        public string Timestamp { get; set; }
    }
}
