//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZS2ServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_role_domain
    {
        public int DMRoleDomainID { get; set; }
        public string Description { get; set; }
    
        public virtual authorized_dm authorized_dm { get; set; }
    }
}
