//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZS2ServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class key_item_domain
    {
        public key_item_domain()
        {
            this.quests = new HashSet<quest>();
            this.quests1 = new HashSet<quest>();
            this.quests2 = new HashSet<quest>();
            this.quests3 = new HashSet<quest>();
            this.quests4 = new HashSet<quest>();
            this.quests5 = new HashSet<quest>();
            this.quests6 = new HashSet<quest>();
            this.player_key_items = new HashSet<player_key_items>();
        }
    
        public int KeyItemID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int KeyItemCategoryID { get; set; }
    
        public virtual ICollection<quest> quests { get; set; }
        public virtual ICollection<quest> quests1 { get; set; }
        public virtual ICollection<quest> quests2 { get; set; }
        public virtual ICollection<quest> quests3 { get; set; }
        public virtual ICollection<quest> quests4 { get; set; }
        public virtual ICollection<quest> quests5 { get; set; }
        public virtual ICollection<quest> quests6 { get; set; }
        public virtual key_item_category_domain key_item_category_domain { get; set; }
        public virtual ICollection<player_key_items> player_key_items { get; set; }
    }
}
