//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZS2ServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class key_item_category_domain
    {
        public key_item_category_domain()
        {
            this.key_item_domain = new HashSet<key_item_domain>();
        }
    
        public int KeyItemCategoryID { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<key_item_domain> key_item_domain { get; set; }
    }
}
