//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZS2ServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int LoginHistoryID { get; set; }
        public int PlayerCharacterID { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual PlayerCharacter PlayerCharacter { get; set; }
    }
}
