//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZS2ServerLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MZS2Context : DbContext
    {
        public MZS2Context()
            : base("name=MZS2Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<craft_blueprints> craft_blueprints { get; set; }
        public DbSet<craft_components> craft_components { get; set; }
        public DbSet<dm_log> dm_log { get; set; }
        public DbSet<pc_corpse> pc_corpse { get; set; }
        public DbSet<pwdata> pwdatas { get; set; }
        public DbSet<pwobjdata> pwobjdatas { get; set; }
        public DbSet<zst_storage> zst_storage { get; set; }
        public DbSet<zsttemplate> zsttemplates { get; set; }
        public DbSet<PlayerCharacter> PlayerCharacters { get; set; }
        public DbSet<LoginHistory> LoginHistories { get; set; }
    }
}
