//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZS2ServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class pc_corpse
    {
        public long ID { get; set; }
        public string CorpseName { get; set; }
        public string Location { get; set; }
        public byte[] StorageNPC { get; set; }
    }
}
