//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZS2ServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_info
    {
        public string Account { get; set; }
        public string IP_Address { get; set; }
        public string CDKey { get; set; }
        public string CharName { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
