//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZS2ServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_key_items
    {
        public int PlayerKeyItemID { get; set; }
        public int PlayerCharacterID { get; set; }
        public int KeyItemID { get; set; }
        public System.DateTime CreateTimestamp { get; set; }
    
        public virtual key_item_domain key_item_domain { get; set; }
    }
}
