//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZS2ServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class pwdata
    {
        public string player { get; set; }
        public string tag { get; set; }
        public string name { get; set; }
        public string val { get; set; }
        public Nullable<int> expire { get; set; }
        public System.DateTime last { get; set; }
    }
}
