//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZS2ServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_kill_groups
    {
        public quest_kill_groups()
        {
            this.quests = new HashSet<quest>();
            this.quests1 = new HashSet<quest>();
            this.quests2 = new HashSet<quest>();
            this.quests3 = new HashSet<quest>();
            this.quests4 = new HashSet<quest>();
        }
    
        public int QuestKillGroupID { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<quest> quests { get; set; }
        public virtual ICollection<quest> quests1 { get; set; }
        public virtual ICollection<quest> quests2 { get; set; }
        public virtual ICollection<quest> quests3 { get; set; }
        public virtual ICollection<quest> quests4 { get; set; }
    }
}
