//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZS2ServerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class zst_storage
    {
        public string Tag { get; set; }
        public string AreaTag { get; set; }
        public string AreaName { get; set; }
        public byte[] Item1 { get; set; }
        public byte[] Item2 { get; set; }
        public byte[] Item3 { get; set; }
        public byte[] Item4 { get; set; }
        public byte[] Item5 { get; set; }
        public byte[] Item6 { get; set; }
        public byte[] Item7 { get; set; }
        public byte[] Item8 { get; set; }
        public byte[] Item9 { get; set; }
        public byte[] Item10 { get; set; }
        public byte[] Item11 { get; set; }
        public byte[] Item12 { get; set; }
        public byte[] Item13 { get; set; }
        public byte[] Item14 { get; set; }
        public byte[] Item15 { get; set; }
        public byte[] Item16 { get; set; }
        public byte[] Item17 { get; set; }
        public byte[] Item18 { get; set; }
        public byte[] Item19 { get; set; }
        public byte[] Item20 { get; set; }
        public byte[] Item21 { get; set; }
        public byte[] Item22 { get; set; }
        public byte[] Item23 { get; set; }
        public byte[] Item24 { get; set; }
        public byte[] Item25 { get; set; }
        public byte[] Item26 { get; set; }
        public byte[] Item27 { get; set; }
        public byte[] Item28 { get; set; }
        public byte[] Item29 { get; set; }
        public byte[] Item30 { get; set; }
        public byte[] Item31 { get; set; }
        public byte[] Item32 { get; set; }
        public byte[] Item33 { get; set; }
        public byte[] Item34 { get; set; }
        public byte[] Item35 { get; set; }
        public byte[] Item36 { get; set; }
        public byte[] Item37 { get; set; }
        public byte[] Item38 { get; set; }
        public byte[] Item39 { get; set; }
        public byte[] Item40 { get; set; }
        public byte[] Item41 { get; set; }
        public byte[] Item42 { get; set; }
        public byte[] Item43 { get; set; }
        public byte[] Item44 { get; set; }
        public byte[] Item45 { get; set; }
        public byte[] Item46 { get; set; }
        public byte[] Item47 { get; set; }
        public byte[] Item48 { get; set; }
        public byte[] Item49 { get; set; }
        public byte[] Item50 { get; set; }
        public byte[] Item51 { get; set; }
        public byte[] Item52 { get; set; }
        public byte[] Item53 { get; set; }
        public byte[] Item54 { get; set; }
        public byte[] Item55 { get; set; }
        public byte[] Item56 { get; set; }
        public byte[] Item57 { get; set; }
        public byte[] Item58 { get; set; }
        public byte[] Item59 { get; set; }
        public byte[] Item60 { get; set; }
        public byte[] Item61 { get; set; }
        public byte[] Item62 { get; set; }
        public byte[] Item63 { get; set; }
        public byte[] Item64 { get; set; }
        public byte[] Item65 { get; set; }
        public byte[] Item66 { get; set; }
        public byte[] Item67 { get; set; }
        public byte[] Item68 { get; set; }
        public byte[] Item69 { get; set; }
        public byte[] Item70 { get; set; }
        public byte[] Item71 { get; set; }
        public byte[] Item72 { get; set; }
        public byte[] Item73 { get; set; }
        public byte[] Item74 { get; set; }
        public byte[] Item75 { get; set; }
        public byte[] Item76 { get; set; }
        public byte[] Item77 { get; set; }
        public byte[] Item78 { get; set; }
        public byte[] Item79 { get; set; }
        public byte[] Item80 { get; set; }
        public byte[] Item81 { get; set; }
        public byte[] Item82 { get; set; }
        public byte[] Item83 { get; set; }
        public byte[] Item84 { get; set; }
        public byte[] Item85 { get; set; }
        public byte[] Item86 { get; set; }
        public byte[] Item87 { get; set; }
        public byte[] Item88 { get; set; }
        public byte[] Item89 { get; set; }
        public byte[] Item90 { get; set; }
        public byte[] Item91 { get; set; }
        public byte[] Item92 { get; set; }
        public byte[] Item93 { get; set; }
        public byte[] Item94 { get; set; }
        public byte[] Item95 { get; set; }
        public byte[] Item96 { get; set; }
        public byte[] Item97 { get; set; }
        public byte[] Item98 { get; set; }
        public byte[] Item99 { get; set; }
        public byte[] Item100 { get; set; }
    }
}
